[2025-10-06T09:25:39.432+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-10-06T09:24:34.575331+00:00 [queued]>
[2025-10-06T09:25:39.437+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-10-06T09:24:34.575331+00:00 [queued]>
[2025-10-06T09:25:39.437+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-10-06T09:25:39.442+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-10-06 09:24:34.575331+00:00
[2025-10-06T09:25:39.445+0000] {standard_task_runner.py:57} INFO - Started process 55 to run task
[2025-10-06T09:25:39.446+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2025-10-06T09:24:34.575331+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpw1h59_cw']
[2025-10-06T09:25:39.447+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask stream_data_from_api
[2025-10-06T09:25:39.475+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2025-10-06T09:24:34.575331+00:00 [running]> on host bf3be0b6e359
[2025-10-06T09:25:39.510+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T09:24:34.575331+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-06T09:24:34.575331+00:00'
[2025-10-06T09:25:39.961+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.7', 29092)]>: connecting to broker:29092 [('172.18.0.7', 29092) IPv4]
[2025-10-06T09:25:39.968+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 29092)]>: Broker version identified as 2.6
[2025-10-06T09:25:39.969+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Connection complete.
[2025-10-06T09:25:40.364+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.7', 29092)]>: connecting to broker:29092 [('172.18.0.7', 29092) IPv4]
[2025-10-06T09:25:40.366+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Connection complete.
[2025-10-06T09:25:40.366+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Closing connection. 
[2025-10-06T09:25:45.968+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:47.055+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:48.500+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:50.053+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:51.567+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:53.095+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:54.593+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:56.528+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:58.005+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:25:59.059+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:00.570+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:02.545+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:04.475+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:05.559+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:07.055+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:09.077+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:10.524+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:11.979+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:13.112+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:14.564+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:15.979+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:17.486+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:18.567+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:20.040+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:21.564+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:23.038+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:24.578+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:26.496+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:28.017+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:29.533+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:31.032+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:32.531+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:34.083+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:36.563+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:38.078+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:40.011+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:26:40.013+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Closing connection. 
[2025-10-06T09:26:40.015+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-10-06T09:26:40.043+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20251006T092434, start_date=20251006T092539, end_date=20251006T092640
[2025-10-06T09:26:40.075+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-10-06T09:26:40.091+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
