[2025-10-06T08:57:54.324+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-10-06T08:55:43.733302+00:00 [queued]>
[2025-10-06T08:57:54.327+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-10-06T08:55:43.733302+00:00 [queued]>
[2025-10-06T08:57:54.327+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-10-06T08:57:54.331+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-10-06 08:55:43.733302+00:00
[2025-10-06T08:57:54.333+0000] {standard_task_runner.py:57} INFO - Started process 41 to run task
[2025-10-06T08:57:54.334+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2025-10-06T08:55:43.733302+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpczcgcrew']
[2025-10-06T08:57:54.335+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask stream_data_from_api
[2025-10-06T08:57:54.356+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2025-10-06T08:55:43.733302+00:00 [running]> on host b4e1875897bf
[2025-10-06T08:57:54.393+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T08:55:43.733302+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-06T08:55:43.733302+00:00'
[2025-10-06T08:57:54.806+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.7', 29092)]>: connecting to broker:29092 [('172.18.0.7', 29092) IPv4]
[2025-10-06T08:57:54.812+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 29092)]>: Broker version identified as 2.6
[2025-10-06T08:57:54.813+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Connection complete.
[2025-10-06T08:57:55.159+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.7', 29092)]>: connecting to broker:29092 [('172.18.0.7', 29092) IPv4]
[2025-10-06T08:57:55.159+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Connection complete.
[2025-10-06T08:57:55.159+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Closing connection. 
[2025-10-06T08:58:00.030+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:01.462+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:02.577+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:04.040+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:05.979+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:07.622+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:09.560+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:11.002+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:12.058+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:13.552+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:14.986+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:17.053+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:19.077+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:21.128+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:22.966+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:24.436+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:25.511+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:27.460+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:28.539+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:30.521+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:32.060+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:34.464+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:36.493+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:38.018+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:39.560+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:41.019+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:42.418+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:43.516+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:44.935+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:46.066+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:48.538+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:52.050+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:53.477+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:55.054+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:58:55.055+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Closing connection. 
[2025-10-06T08:58:55.056+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-10-06T08:58:55.070+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20251006T085543, start_date=20251006T085754, end_date=20251006T085855
[2025-10-06T08:58:55.101+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-10-06T08:58:55.124+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
