[2025-10-06T08:56:51.859+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-10-06T08:54:56.021831+00:00 [queued]>
[2025-10-06T08:56:51.864+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-10-06T08:54:56.021831+00:00 [queued]>
[2025-10-06T08:56:51.864+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-10-06T08:56:51.875+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-10-06 08:54:56.021831+00:00
[2025-10-06T08:56:51.878+0000] {standard_task_runner.py:57} INFO - Started process 36 to run task
[2025-10-06T08:56:51.881+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2025-10-06T08:54:56.021831+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpf2p73vrk']
[2025-10-06T08:56:51.882+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask stream_data_from_api
[2025-10-06T08:56:51.937+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2025-10-06T08:54:56.021831+00:00 [running]> on host b4e1875897bf
[2025-10-06T08:56:51.979+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T08:54:56.021831+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-06T08:54:56.021831+00:00'
[2025-10-06T08:56:52.450+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.7', 29092)]>: connecting to broker:29092 [('172.18.0.7', 29092) IPv4]
[2025-10-06T08:56:52.454+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 29092)]>: Broker version identified as 2.6
[2025-10-06T08:56:52.454+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Connection complete.
[2025-10-06T08:56:52.858+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.7', 29092)]>: connecting to broker:29092 [('172.18.0.7', 29092) IPv4]
[2025-10-06T08:56:52.859+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Connection complete.
[2025-10-06T08:56:52.860+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Closing connection. 
[2025-10-06T08:56:58.487+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:56:59.547+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:01.026+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:02.517+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:03.974+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:05.057+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:06.583+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:08.472+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:10.047+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:11.488+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:12.941+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:14.040+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:15.589+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:17.494+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:18.911+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:19.995+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:23.580+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:25.019+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:26.480+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:27.988+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:29.520+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:31.001+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:32.594+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:34.545+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:35.995+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:37.502+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:39.052+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:40.472+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:43.975+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:45.494+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:48.053+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:50.052+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:52.025+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:57:52.872+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Closing connection. 
[2025-10-06T08:57:52.875+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-10-06T08:57:52.896+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20251006T085456, start_date=20251006T085651, end_date=20251006T085752
[2025-10-06T08:57:52.946+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-10-06T08:57:52.961+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
