[2025-10-06T09:43:43.117+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-10-06T09:42:38.134478+00:00 [queued]>
[2025-10-06T09:43:43.122+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-10-06T09:42:38.134478+00:00 [queued]>
[2025-10-06T09:43:43.122+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-10-06T09:43:43.127+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-10-06 09:42:38.134478+00:00
[2025-10-06T09:43:43.131+0000] {standard_task_runner.py:57} INFO - Started process 62 to run task
[2025-10-06T09:43:43.133+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2025-10-06T09:42:38.134478+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpyt5tvwxi']
[2025-10-06T09:43:43.134+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask stream_data_from_api
[2025-10-06T09:43:43.179+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2025-10-06T09:42:38.134478+00:00 [running]> on host 24002ed0955a
[2025-10-06T09:43:43.226+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T09:42:38.134478+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-06T09:42:38.134478+00:00'
[2025-10-06T09:43:43.653+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.7', 29092)]>: connecting to broker:29092 [('172.18.0.7', 29092) IPv4]
[2025-10-06T09:43:43.661+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 29092)]>: Broker version identified as 2.6
[2025-10-06T09:43:43.662+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Connection complete.
[2025-10-06T09:43:44.044+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.7', 29092)]>: connecting to broker:29092 [('172.18.0.7', 29092) IPv4]
[2025-10-06T09:43:44.046+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Connection complete.
[2025-10-06T09:43:44.047+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Closing connection. 
[2025-10-06T09:43:50.393+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:52.784+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:54.323+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:55.873+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:57.846+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:43:59.750+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:00.819+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:02.278+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:03.760+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:05.257+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:06.774+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:08.303+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:09.821+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:11.308+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:13.249+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:14.839+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:16.773+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:17.848+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:19.308+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:21.380+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:23.229+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:24.354+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:25.816+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:27.318+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:29.292+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:30.789+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:33.259+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:34.765+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:36.338+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:39.232+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:40.928+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:42.839+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T09:44:43.980+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.7', 29092)]>: Closing connection. 
[2025-10-06T09:44:43.982+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-10-06T09:44:44.008+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20251006T094238, start_date=20251006T094343, end_date=20251006T094444
[2025-10-06T09:44:44.050+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-10-06T09:44:44.064+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
