[2025-10-06T08:15:18.267+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-10-06T08:14:13.587174+00:00 [queued]>
[2025-10-06T08:15:18.270+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-10-06T08:14:13.587174+00:00 [queued]>
[2025-10-06T08:15:18.270+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-10-06T08:15:18.274+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-10-06 08:14:13.587174+00:00
[2025-10-06T08:15:18.276+0000] {standard_task_runner.py:57} INFO - Started process 37 to run task
[2025-10-06T08:15:18.277+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2025-10-06T08:14:13.587174+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpulux5kdm']
[2025-10-06T08:15:18.278+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask stream_data_from_api
[2025-10-06T08:15:18.299+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2025-10-06T08:14:13.587174+00:00 [running]> on host b06bf3f6accc
[2025-10-06T08:15:18.330+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T08:14:13.587174+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-06T08:14:13.587174+00:00'
[2025-10-06T08:15:18.766+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.8', 29092)]>: connecting to broker:29092 [('172.18.0.8', 29092) IPv4]
[2025-10-06T08:15:18.772+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('172.18.0.8', 29092)]>: Broker version identified as 2.6
[2025-10-06T08:15:18.772+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.8', 29092)]>: Connection complete.
[2025-10-06T08:15:19.176+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.8', 29092)]>: connecting to broker:29092 [('172.18.0.8', 29092) IPv4]
[2025-10-06T08:15:19.177+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.8', 29092)]>: Connection complete.
[2025-10-06T08:15:19.178+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.8', 29092)]>: Closing connection. 
[2025-10-06T08:15:24.876+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:26.356+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:27.875+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:29.374+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:30.919+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:33.402+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:36.371+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:37.835+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:38.881+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:40.297+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:41.393+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:42.874+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:43.932+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:45.428+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:46.867+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:48.415+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:50.849+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:52.339+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:53.431+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:54.874+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:56.444+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:15:58.437+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:16:00.357+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:16:01.871+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:16:03.320+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:16:04.430+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:16:08.302+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:16:09.370+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:16:10.865+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:16:12.296+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:16:13.422+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:16:14.876+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:16:16.413+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:16:18.376+0000] {kafka_stream.py:61} ERROR - An error occured: list index out of range
[2025-10-06T08:16:19.110+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.8', 29092)]>: Closing connection. 
[2025-10-06T08:16:19.111+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-10-06T08:16:19.127+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20251006T081413, start_date=20251006T081518, end_date=20251006T081619
[2025-10-06T08:16:19.159+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-10-06T08:16:19.172+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
